// <auto-generated />
using System;
using DeskBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeskBookingAPI.Migrations
{
    [DbContext(typeof(DeskBookingContext))]
    [Migration("20250530195038_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeskBookingAPI.Models.BookingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("Capacity")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd"),
                            Amenities = new[] { "Conditioning", "Play", "Wi-Fi", "Coffee" },
                            Capacity = new int[0],
                            Name = "Open Space",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372"),
                            Amenities = new[] { "Wi-Fi", "Conditioning", "Music" },
                            Capacity = new[] { 1, 2, 5, 10 },
                            Name = "Private Room",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("51de8af8-a981-49d9-a276-8144384555bb"),
                            Amenities = new[] { "Wi-Fi", "Conditioning", "Music", "Micro" },
                            Capacity = new[] { 10, 20 },
                            Name = "Meeting Room",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceAvailabilityOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03d742f8-2494-407b-97ec-ebf3b7c14720"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("05a2f6d4-1df8-4ba7-b6e0-b96382eccc48"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("17b73954-d941-4b04-8e66-181c5a38dc1f"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("de873ec6-5095-4096-b4d7-5ffd8837ccea"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("05192287-1759-4fe6-9762-e241967386b9"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("0a6e9e4e-e369-4450-aae8-2b168e62679b"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11a29aa8-2e0d-4c6c-8452-c73ab7ed72bb"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("57d352b0-06a9-4bc8-930a-6a013c47f3fa"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("0fe5759f-c080-451c-9db0-7fdcc4a20888"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("0722764f-6f83-4b1a-9d2c-97ea351bb77e"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("3a0bc226-1e63-444a-acd8-2f8a7a516ba4"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("63cee1d2-5475-42d3-97df-75945111160f"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("059ffa7c-0826-4f9e-accb-42907db4af39"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("d2c32153-10b1-42ad-8762-3c731517b00e"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("930b50a5-4ff3-4b57-b485-4779ffc7a8f9"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("5fc3d91f-6adf-471a-b5d7-ec2e38919a67"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("97d00c25-1678-4ed8-a2f2-74c553df2e4d"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("52f983d7-2abe-40f1-990a-39082d48b4a5"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("e4b0439c-c603-438d-9c48-3e89944b7221"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("04d993b9-3619-4a99-9fd7-4793855483d8"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("97d33b28-05e2-469a-8d58-584281de25c2"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("bf2309fd-28c8-49ea-8fc1-eb050a33f101"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("d2a06741-4b55-4f2f-9469-73e64edcf1bf"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("2a11af56-40b4-46f5-bcd9-237cf8b80b65"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("91bbfdb5-5cbb-48ee-9f07-cf33ada7bbc4"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("793d278d-4fca-4afb-9f49-640129b30804"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("9f5163fb-1e9a-4ea3-b5cf-f59d351c4f33"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("490385ef-b660-451f-ad9b-3cb9bb95b6f5"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("694c8584-bbb0-4c9e-a097-52ea60c1f0e8"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("9717cd48-954e-4a32-99ad-02e50a2da90e"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("95d4b90e-4986-493c-9398-c17961b537e0"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("7d116299-bec6-468a-94c9-dbcb49fddbd3"),
                            Capacity = 2,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("84adf783-4b7c-4c44-b7e3-982e5e659105"),
                            Capacity = 2,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("6ef6be20-20c4-47bb-8486-18be2393f02d"),
                            Capacity = 2,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("a50182d1-83d9-43fd-9640-89ffb94a2975"),
                            Capacity = 2,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("411b0df1-d4b9-4f98-94a2-91d0e20452fc"),
                            Capacity = 5,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("e9a01b0c-4caf-4d98-bbe8-5f3171a974df"),
                            Capacity = 5,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("3c024e8c-9472-492a-9075-6184c3b190e6"),
                            Capacity = 5,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("818b7488-9f73-4159-88db-11504e21caef"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("0267e785-ccac-4512-9d93-5eb8d90e6f40"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        },
                        new
                        {
                            Id = new Guid("37d8909d-0132-4646-9da7-699a1399114e"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        },
                        new
                        {
                            Id = new Guid("2d5808e7-5a50-46ce-81d7-6f00fdf7a36e"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        },
                        new
                        {
                            Id = new Guid("185cedd3-7101-4373-88f1-1975ae0a4e53"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        },
                        new
                        {
                            Id = new Guid("cdfcfab1-11fa-496a-82c3-810a95a35918"),
                            Capacity = 20,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        });
                });

            modelBuilder.Entity("DeskBookingAPI.Models.BookingModel", b =>
                {
                    b.HasOne("DeskBookingAPI.Models.WorkspaceAvailabilityOption", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskBookingAPI.Models.Workspace", "Workspace")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.HasOne("DeskBookingAPI.Models.Workspace", "Workspace")
                        .WithMany("AvailabilityOptions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.Workspace", b =>
                {
                    b.Navigation("AvailabilityOptions");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
