// <auto-generated />
using System;
using DeskBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeskBookingAPI.Migrations
{
    [DbContext(typeof(DeskBookingContext))]
    partial class DeskBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeskBookingAPI.Models.BookingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("Capacity")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd"),
                            Amenities = new[] { "Conditioning", "Play", "Wi-Fi", "Coffee" },
                            Capacity = new int[0],
                            Name = "Open Space",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372"),
                            Amenities = new[] { "Wi-Fi", "Conditioning", "Music" },
                            Capacity = new[] { 1, 2, 5, 10 },
                            Name = "Private Room",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("51de8af8-a981-49d9-a276-8144384555bb"),
                            Amenities = new[] { "Wi-Fi", "Conditioning", "Music", "Micro" },
                            Capacity = new[] { 10, 20 },
                            Name = "Meeting Room",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceAvailabilityOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111131"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111132"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111133"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111134"),
                            Capacity = 0,
                            UnitType = "desk",
                            WorkspaceId = new Guid("f1d76f62-e4ff-4b68-82d7-9733fb57f3bd")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Capacity = 1,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Capacity = 2,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Capacity = 5,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("b2844205-b49b-4cf1-8389-b7cdb0a54372")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333310"),
                            Capacity = 10,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333320"),
                            Capacity = 20,
                            UnitType = "room",
                            WorkspaceId = new Guid("51de8af8-a981-49d9-a276-8144384555bb")
                        });
                });

            modelBuilder.Entity("DeskBookingAPI.Models.BookingModel", b =>
                {
                    b.HasOne("DeskBookingAPI.Models.WorkspaceAvailabilityOption", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskBookingAPI.Models.Workspace", "Workspace")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.HasOne("DeskBookingAPI.Models.Workspace", "Workspace")
                        .WithMany("AvailabilityOptions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.Workspace", b =>
                {
                    b.Navigation("AvailabilityOptions");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DeskBookingAPI.Models.WorkspaceAvailabilityOption", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
